#!/usr/bin/env bash
#
#启动测试使用的nginx
if [ $# -eq 0 ]||[ $1 = "nginx" ]
then
killall nginx||true
nginx -c /media/data/编程/Project/webbookmark/webbookmark-nginx.conf
fi
if [ $# -eq 0 ]||[ $1 = "uwsgi" ]
then
killall uwsgi||true
uwsgi --ini /media/data/编程/Project/webbookmark/webbookmark-uwsgi.ini
fi
